name: Cypress Test for Plume Shop
on: [push]

jobs:
  _Chrome:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run integration tests with cypress X Chrome
        uses: cypress-io/github-action@v2.9.7
        id: cypress
        with: 
          build: npx cypress info
          start: cypress open
          browser: chrome
      - name: Get-Results
        uses: ./ # URL TO ACTION
        with: 
          cypress_chrome: ${{ steps.cypress-tests.outcome }}
  

  _Firefox: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run itegration tests with cypress X firefox
        uses: cypress-io/github-action@v2
        with:
          start: cypress open
          browser: firefox
  

  


